In [101]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV
import matplotlib.font_manager as fm

In [102]:

plt.rc('font', family='NanumBarunGothic')
font_location = 'C:/Windows/Fonts/MALGUNSL.TTF'  # for windows
font_name = fm.FontProperties(fname=font_location).get_name()
plt.rc('font', family=font_name)

In [10]:
company_info = pd.read_csv(r'C:\Users\yoon9\Documents\GitHub\numble_repo\data\company_info_with_days.csv',encoding='cp949')

In [11]:
company_info['기업명']

0                 한일가스산업
1                   엠피아이
2                   도영운수
3                   중원산업
4                  카타나골프
              ...       
35716            게방식당팩토리
35717           우진푸드중부지점
35718    윤월드푸드코리아다크써클브로스
35719               기린테크
35720               우리로봇
Name: 기업명, Length: 35721, dtype: object

# Feature Engineering

In [12]:
df = company_info.drop(columns=['사업자등록번호','기업명','업종','설립일자','주요사업내용','산업코드1','공기업구분'])

In [13]:
df.columns

Index(['개인법인구분', '본점지점구분', '국외투자법인여부', '벤처기업여부', '상장코드', '공공기관유형', '중견기업보호여부',
       '본점기업코드', '설립구분', '국가명', '직원수', '폐업여부', '산업코드 대분류', '회사설립일'],
      dtype='object')

## 스케일링 인코딩 진행

In [103]:
from sklearn.preprocessing import StandardScaler # 스케일링 라이브러리
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler

In [104]:
company_info

사업자등록번호              기업명 업종  공기업구분  개인법인구분  본점지점구분  국외투자법인여부  \
0      1138111739           한일가스산업  M      2       1       1         0   
1      2078132193             엠피아이  M      2       1       1         0   
2      1318167565             도영운수  M      2       1       1         0   
3      5048128251             중원산업  M      2       1       1         0   
4      1098164260            카타나골프  M      2       1       1         0   
...           ...              ... ..    ...     ...     ...       ...   
35716  4808501629          게방식당팩토리  M      2       1       2         0   
35717  8018501578         우진푸드중부지점  M      2       1       2         0   
35718  4118523419  윤월드푸드코리아다크써클브로스  M      2       1       2         0   
35719  1738102533             기린테크  M      2       1       1         0   
35720  3138135248             우리로봇  M      2       1       1         0   

       벤처기업여부  상장코드  산업코드1  ...  중견기업보호여부  본점기업코드                 설립일자 설립구분  \
0           0     0     47  ...         0       0  1966-04-19 00:00:00    1   
1           0     0     15  ...         0       0  1991-08-06 00:00:00    1   
2           0     0     49  ...         0       0  2001-10-30 00:00:00    1   
3           0     0     30  ...         0       0  1999-01-12 00:00:00    1   
4           0     0     46  ...         0       0  2000-05-31 00:00:00    1   
...       ...   ...    ...  ...       ...     ...                  ...  ...   
35716       0     0     10  ...         0       1  2018-01-26 00:00:00    1   
35717       0     0     10  ...         0       1  2020-07-27 00:00:00    1   
35718       0     0     56  ...         0       1  2019-09-26 00:00:00    1   
35719       0     0     58  ...         0       0  2021-10-25 00:00:00    1   
35720       1     0     29  ...         0       0  2020-06-29 00:00:00    1   

                         주요사업내용 국가명    직원수  폐업여부   산업코드 대분류  회사설립일  
0               LP Gas 충전 및 판매업   0   43.0     0   도매 및 소매업  20650  
1               가죽 및 대용가죽제품 제조업   0   35.0     0        제조업  11410  
2                         시내버스업   0  149.0     0   운수 및 창고업   7672  
3                     자동차 부품 제조   0   75.0     0        제조업   8694  
4             골프용품 전반의 제조 및 수출업   0    3.0     0   도매 및 소매업   8189  
...                         ...  ..    ...   ...        ...    ...  
35716                  간장게장(장류)   0    0.0     1        제조업   1740  
35717            돈가스, 탕수육, 꿔바로우   0   22.0     1        제조업    827  
35718                    한식, 중식   0    0.0     1  숙박 및 음식점업   1132  
35719  1.인공지능(AI) 솔루션 구축 및 관련사업   0    0.0     1      정보통신업    372  
35720                       NaN   0    0.0     1        제조업    855  

[35721 rows x 21 columns]

In [16]:
num_attribss = df[['직원수','회사설립일']]
cat_1hot_attribs = df[['산업코드 대분류','국외투자법인여부','개인법인구분','본점지점구분','본점기업코드','설립구분']]
cat_ord_attribs = df[['상장코드','벤처기업여부','공공기관유형', '중견기업보호여부','국가명']]
y = company_info[['폐업여부']]
# 변수별 타입 나누기

## 스케일링

### StandardScaler

In [17]:
# 수치형 변수 스케일링
sta_scaler = StandardScaler()
sta_X_scale = sta_scaler.fit_transform(num_attribss)
sta_X_scale = pd.DataFrame(sta_X_scale, columns=num_attribss.columns)
sta_X_scale  # 스케일링 데이터 프레임화

직원수     회사설립일
0     -0.071824  3.515949
1     -0.123865  1.242839
2      0.617721  0.323263
3      0.136341  0.574683
4     -0.332029  0.450449
...         ...       ...
35716 -0.351545 -1.136054
35717 -0.208432 -1.360659
35718 -0.351545 -1.285626
35719 -0.351545 -1.472592
35720 -0.351545 -1.353770

[35721 rows x 2 columns]

# MinMaxScaler

In [18]:
MM_scaler = MinMaxScaler()
MM_X_scale = MM_scaler.fit_transform(num_attribss)
MM_X_scale = pd.DataFrame(MM_X_scale, columns=num_attribss.columns)
MM_X_scale  # 스케일링 데이터 프레임화

직원수     회사설립일
0      0.002636  0.414897
1      0.002146  0.228227
2      0.009135  0.152710
3      0.004598  0.173357
4      0.000184  0.163155
...         ...       ...
35716  0.000000  0.032869
35717  0.001349  0.014425
35718  0.000000  0.020586
35719  0.000000  0.005232
35720  0.000000  0.014990

[35721 rows x 2 columns]

## 인코딩

In [19]:
# 원핫인코딩 함수 적용
hot1_encoder = OneHotEncoder(sparse=False,drop='if_binary')
X_1hot = hot1_encoder.fit_transform(cat_1hot_attribs)
X_1hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
X_1hot = pd.DataFrame(X_1hot, columns=hot1_encoder.get_feature_names()) #순서가 없는 카테고리형
# 데이터 프레임화

C:\Users\yoon9\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [21]:
X_1hot

x0_건설업  x0_공공 행정, 국방 및 사회보장 행정  x0_광업  x0_교육 서비스업  x0_금융 및 보험업  \
0         0.0                     0.0    0.0         0.0          0.0   
1         0.0                     0.0    0.0         0.0          0.0   
2         0.0                     0.0    0.0         0.0          0.0   
3         0.0                     0.0    0.0         0.0          0.0   
4         0.0                     0.0    0.0         0.0          0.0   
...       ...                     ...    ...         ...          ...   
35716     0.0                     0.0    0.0         0.0          0.0   
35717     0.0                     0.0    0.0         0.0          0.0   
35718     0.0                     0.0    0.0         0.0          0.0   
35719     0.0                     0.0    0.0         0.0          0.0   
35720     0.0                     0.0    0.0         0.0          0.0   

       x0_농업,임업 및 어업  x0_도매 및 소매업  x0_보건업 및 사회복지 서비스업  x0_부동산업  \
0                0.0          1.0                 0.0      0.0   
1                0.0          0.0                 0.0      0.0   
2                0.0          0.0                 0.0      0.0   
3                0.0          0.0                 0.0      0.0   
4                0.0          1.0                 0.0      0.0   
...              ...          ...                 ...      ...   
35716            0.0          0.0                 0.0      0.0   
35717            0.0          0.0                 0.0      0.0   
35718            0.0          0.0                 0.0      0.0   
35719            0.0          0.0                 0.0      0.0   
35720            0.0          0.0                 0.0      0.0   

       x0_사업시설 관리, 사업 지원 및 임대 서비스업  ...  x3_2  x4_1  x5_1  x5_2  x5_4  x5_5  \
0                              0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   
1                              0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   
2                              0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   
3                              0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   
4                              0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   
...                            ...  ...   ...   ...   ...   ...   ...   ...   
35716                          0.0  ...   1.0   1.0   1.0   0.0   0.0   0.0   
35717                          0.0  ...   1.0   1.0   1.0   0.0   0.0   0.0   
35718                          0.0  ...   1.0   1.0   1.0   0.0   0.0   0.0   
35719                          0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   
35720                          0.0  ...   0.0   0.0   1.0   0.0   0.0   0.0   

       x5_6  x5_7  x5_10  x5_99  
0       0.0   0.0    0.0    0.0  
1       0.0   0.0    0.0    0.0  
2       0.0   0.0    0.0    0.0  
3       0.0   0.0    0.0    0.0  
4       0.0   0.0    0.0    0.0  
...     ...   ...    ...    ...  
35716   0.0   0.0    0.0    0.0  
35717   0.0   0.0    0.0    0.0  
35718   0.0   0.0    0.0    0.0  
35719   0.0   0.0    0.0    0.0  
35720   0.0   0.0    0.0    0.0  

[35721 rows x 31 columns]

In [22]:
ord_encoder = OrdinalEncoder() #순서가 있는 카테고리형
X_ord = ord_encoder.fit_transform(cat_ord_attribs)
X_ord = pd.DataFrame(X_ord, columns= ['상장코드','벤처기업여부','공공기관유형', '중견기업보호여부','국가명'])
X_ord

상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명
0       0.0     0.0     0.0       0.0  0.0
1       0.0     0.0     0.0       0.0  0.0
2       0.0     0.0     0.0       0.0  0.0
3       0.0     0.0     0.0       0.0  0.0
4       0.0     0.0     0.0       0.0  0.0
...     ...     ...     ...       ...  ...
35716   0.0     0.0     0.0       0.0  0.0
35717   0.0     0.0     0.0       0.0  0.0
35718   0.0     0.0     0.0       0.0  0.0
35719   0.0     0.0     0.0       0.0  0.0
35720   0.0     1.0     0.0       0.0  0.0

[35721 rows x 5 columns]

In [23]:
df_preprdcessed_sta = pd.concat([sta_X_scale, X_1hot, X_ord], axis = 1)
df_preprdcessed_sta
#최종 데이터 합치기

직원수     회사설립일  x0_건설업  x0_공공 행정, 국방 및 사회보장 행정  x0_광업  x0_교육 서비스업  \
0     -0.071824  3.515949     0.0                     0.0    0.0         0.0   
1     -0.123865  1.242839     0.0                     0.0    0.0         0.0   
2      0.617721  0.323263     0.0                     0.0    0.0         0.0   
3      0.136341  0.574683     0.0                     0.0    0.0         0.0   
4     -0.332029  0.450449     0.0                     0.0    0.0         0.0   
...         ...       ...     ...                     ...    ...         ...   
35716 -0.351545 -1.136054     0.0                     0.0    0.0         0.0   
35717 -0.208432 -1.360659     0.0                     0.0    0.0         0.0   
35718 -0.351545 -1.285626     0.0                     0.0    0.0         0.0   
35719 -0.351545 -1.472592     0.0                     0.0    0.0         0.0   
35720 -0.351545 -1.353770     0.0                     0.0    0.0         0.0   

       x0_금융 및 보험업  x0_농업,임업 및 어업  x0_도매 및 소매업  x0_보건업 및 사회복지 서비스업  ...  x5_5  \
0              0.0            0.0          1.0                 0.0  ...   0.0   
1              0.0            0.0          0.0                 0.0  ...   0.0   
2              0.0            0.0          0.0                 0.0  ...   0.0   
3              0.0            0.0          0.0                 0.0  ...   0.0   
4              0.0            0.0          1.0                 0.0  ...   0.0   
...            ...            ...          ...                 ...  ...   ...   
35716          0.0            0.0          0.0                 0.0  ...   0.0   
35717          0.0            0.0          0.0                 0.0  ...   0.0   
35718          0.0            0.0          0.0                 0.0  ...   0.0   
35719          0.0            0.0          0.0                 0.0  ...   0.0   
35720          0.0            0.0          0.0                 0.0  ...   0.0   

       x5_6  x5_7  x5_10  x5_99  상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명  
0       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
1       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
2       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
3       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
4       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
...     ...   ...    ...    ...   ...     ...     ...       ...  ...  
35716   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35717   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35718   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35719   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35720   0.0   0.0    0.0    0.0   0.0     1.0     0.0       0.0  0.0  

[35721 rows x 38 columns]

In [24]:
df_preprdcessed_MM = pd.concat([MM_X_scale, X_1hot, X_ord], axis = 1)
df_preprdcessed_MM
#최종 데이터 합치기

직원수     회사설립일  x0_건설업  x0_공공 행정, 국방 및 사회보장 행정  x0_광업  x0_교육 서비스업  \
0      0.002636  0.414897     0.0                     0.0    0.0         0.0   
1      0.002146  0.228227     0.0                     0.0    0.0         0.0   
2      0.009135  0.152710     0.0                     0.0    0.0         0.0   
3      0.004598  0.173357     0.0                     0.0    0.0         0.0   
4      0.000184  0.163155     0.0                     0.0    0.0         0.0   
...         ...       ...     ...                     ...    ...         ...   
35716  0.000000  0.032869     0.0                     0.0    0.0         0.0   
35717  0.001349  0.014425     0.0                     0.0    0.0         0.0   
35718  0.000000  0.020586     0.0                     0.0    0.0         0.0   
35719  0.000000  0.005232     0.0                     0.0    0.0         0.0   
35720  0.000000  0.014990     0.0                     0.0    0.0         0.0   

       x0_금융 및 보험업  x0_농업,임업 및 어업  x0_도매 및 소매업  x0_보건업 및 사회복지 서비스업  ...  x5_5  \
0              0.0            0.0          1.0                 0.0  ...   0.0   
1              0.0            0.0          0.0                 0.0  ...   0.0   
2              0.0            0.0          0.0                 0.0  ...   0.0   
3              0.0            0.0          0.0                 0.0  ...   0.0   
4              0.0            0.0          1.0                 0.0  ...   0.0   
...            ...            ...          ...                 ...  ...   ...   
35716          0.0            0.0          0.0                 0.0  ...   0.0   
35717          0.0            0.0          0.0                 0.0  ...   0.0   
35718          0.0            0.0          0.0                 0.0  ...   0.0   
35719          0.0            0.0          0.0                 0.0  ...   0.0   
35720          0.0            0.0          0.0                 0.0  ...   0.0   

       x5_6  x5_7  x5_10  x5_99  상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명  
0       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
1       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
2       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
3       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
4       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
...     ...   ...    ...    ...   ...     ...     ...       ...  ...  
35716   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35717   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35718   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35719   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35720   0.0   0.0    0.0    0.0   0.0     1.0     0.0       0.0  0.0  

[35721 rows x 38 columns]

In [28]:
X = df_preprdcessed_sta

In [30]:
X.shape, y.shape

((35721, 38), (35721, 1))

# train, val 데이터셋 나누기

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, shuffle=True, stratify=y, random_state=42)
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((28576, 38), (7145, 38), (28576, 1), (7145, 1))

In [34]:
y.value_counts()

폐업여부
0       28982
1        6739
dtype: int64

# 모델 평가 함수

In [35]:
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [36]:
def model_eval(pred, answer):
    print(f'accuracy_score : {accuracy_score(pred,answer)}')
    print(f'recall_score : {recall_score(pred,answer)}')
    print(f'precision_score : {precision_score(pred,answer)}')
    print(f'f1_score : {f1_score(pred,answer)}')
    print(f'coufusion_matrix : ')
    print(confusion_matrix(pred,answer))

# 랜덤포레스트 모델 학습

In [37]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
RFC_sta = RandomForestClassifier(max_depth=10,n_estimators=100)

In [57]:
RFC_sta.fit(X_train,y_train)

C:\Users\yoon9\AppData\Local\Temp\ipykernel_13960\1307098183.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFC_sta.fit(X_train,y_train)


RandomForestClassifier(max_depth=10)

In [58]:
X_train_predicted = RFC_sta.predict(X_train)

In [59]:
X_val_predicted = RFC_sta.predict(X_val)

In [60]:
model_eval(X_train_predicted,y_train)

accuracy_score : 0.8606872900335947
recall_score : 0.8344402277039848
precision_score : 0.3262845483212762
f1_score : 0.4691292172289638
coufusion_matrix : 
[[22836  3632]
 [  349  1759]]


In [61]:
model_eval(X_val_predicted,y_val)

accuracy_score : 0.8531840447865641
recall_score : 0.793713163064833
precision_score : 0.2997032640949555
f1_score : 0.43511039310716215
coufusion_matrix : 
[[5692  944]
 [ 105  404]]


### 모델학습

In [66]:
X_MM = df_preprdcessed_MM

In [67]:
y

폐업여부
0         0
1         0
2         0
3         0
4         0
...     ...
35716     1
35717     1
35718     1
35719     1
35720     1

[35721 rows x 1 columns]

In [68]:
X_train_MM, X_val_MM, y_train_MM, y_val_MM = train_test_split(X_MM, y, test_size=0.2, shuffle=True, stratify=y, random_state=42)
X_train_MM.shape, X_val_MM.shape, y_train_MM.shape, y_val_MM.shape

((28576, 38), (7145, 38), (28576, 1), (7145, 1))

In [75]:
RFC_MM = RandomForestClassifier()

In [76]:
RFC_MM.fit(X_train_MM,y_train_MM)

C:\Users\yoon9\AppData\Local\Temp\ipykernel_13960\3340015268.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFC_MM.fit(X_train_MM,y_train_MM)


RandomForestClassifier()

In [77]:
X_train_predicted_MM = RFC_MM.predict(X_train_MM)

In [78]:
X_val_predicted_MM = RFC_MM.predict(X_val_MM)

In [79]:
model_eval(X_train_predicted_MM,y_train_MM)

accuracy_score : 0.9896416573348265
recall_score : 0.9875598086124402
precision_score : 0.9571508069003896
f1_score : 0.9721175584024114
coufusion_matrix : 
[[23120   231]
 [   65  5160]]


In [80]:
model_eval(X_val_predicted_MM,y_val_MM)

accuracy_score : 0.8219734079776068
recall_score : 0.5355140186915888
precision_score : 0.4250741839762611
f1_score : 0.47394540942928043
coufusion_matrix : 
[[5300  775]
 [ 497  573]]


# LightGBM

In [99]:
import lightgbm as lgb

ModuleNotFoundError: No module named 'lightgbm'

In [100]:
# LightGBM 전용 데이터셋 생성
dtrain = lgb.Dataset(X_train, y_train) # LightGBM 전용 훈련 데이터셋
dvalid = lgb.Dataset(X_valid, y_valid) # LightGBM 전용 검증 데이터셋
# LightGBM 모델 훈련
lgb_model = lgb.train(params=max_params, # 최적 하이퍼파라미터 1
                        train_set=dtrain, # 훈련 데이터셋
                        num_boost_round=2500, # 부스팅 반복 횟수
                        valid_sets=dvalid, # 성능 평가용 검증 데이터셋
                        feval=gini, # 검증용 평가지표
                        early_stopping_rounds=300, # 조기종료 조건
                        verbose_eval=100) # 100번째마다 점수 출력

# 테스트 데이터를 활용해 OOF 예측
oof_test_preds += lgb_model.predict(X_test)/folds.n_splits
# 모델 성능 평가를 위한 검증 데이터 타깃값 예측
oof_val_preds[valid_idx] += lgb_model.predict(X_valid)
# 검증 데이터 예측 확률에 대한 정규화 지니계수
gini_score = eval_gini(y_valid, oof_val_preds[valid_idx])
print(f'폴드 {idx+1} 지니계수 : {gini_score}\n')

NameError: name 'lgb' is not defined