In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV
import matplotlib.font_manager as fm

In [3]:

plt.rc('font', family='NanumBarunGothic')
font_location = 'C:/Windows/Fonts/MALGUNSL.TTF'  # for windows
font_name = fm.FontProperties(fname=font_location).get_name()
plt.rc('font', family=font_name)

In [4]:
company_info = pd.read_csv(r'C:\Users\yoon9\Documents\GitHub\numble_repo\data\company_info_with_days.csv',encoding='cp949')

In [5]:
company_info['기업명']

0                 한일가스산업
1                   엠피아이
2                   도영운수
3                   중원산업
4                  카타나골프
              ...       
35716            게방식당팩토리
35717           우진푸드중부지점
35718    윤월드푸드코리아다크써클브로스
35719               기린테크
35720               우리로봇
Name: 기업명, Length: 35721, dtype: object

# Feature Engineering

In [6]:
df = company_info.drop(columns=['사업자등록번호','기업명','업종','설립일자','주요사업내용','산업코드1','공기업구분'])

In [7]:
df.columns

Index(['개인법인구분', '본점지점구분', '국외투자법인여부', '벤처기업여부', '상장코드', '공공기관유형', '중견기업보호여부',
       '본점기업코드', '설립구분', '국가명', '직원수', '폐업여부', '산업코드 대분류', '회사설립일'],
      dtype='object')

## 스케일링 인코딩 진행

In [2]:
from sklearn.preprocessing import StandardScaler # 스케일링 라이브러리
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

ModuleNotFoundError: No module named 'sklearn.preprocessing'

In [9]:
company_info

사업자등록번호              기업명 업종  공기업구분  개인법인구분  본점지점구분  국외투자법인여부  \
0      1138111739           한일가스산업  M      2       1       1         0   
1      2078132193             엠피아이  M      2       1       1         0   
2      1318167565             도영운수  M      2       1       1         0   
3      5048128251             중원산업  M      2       1       1         0   
4      1098164260            카타나골프  M      2       1       1         0   
...           ...              ... ..    ...     ...     ...       ...   
35716  4808501629          게방식당팩토리  M      2       1       2         0   
35717  8018501578         우진푸드중부지점  M      2       1       2         0   
35718  4118523419  윤월드푸드코리아다크써클브로스  M      2       1       2         0   
35719  1738102533             기린테크  M      2       1       1         0   
35720  3138135248             우리로봇  M      2       1       1         0   

       벤처기업여부  상장코드  산업코드1  ...  중견기업보호여부  본점기업코드                 설립일자 설립구분  \
0           0     0     47  ...         0       0  1966-04-19 00:00:00    1   
1           0     0     15  ...         0       0  1991-08-06 00:00:00    1   
2           0     0     49  ...         0       0  2001-10-30 00:00:00    1   
3           0     0     30  ...         0       0  1999-01-12 00:00:00    1   
4           0     0     46  ...         0       0  2000-05-31 00:00:00    1   
...       ...   ...    ...  ...       ...     ...                  ...  ...   
35716       0     0     10  ...         0       1  2018-01-26 00:00:00    1   
35717       0     0     10  ...         0       1  2020-07-27 00:00:00    1   
35718       0     0     56  ...         0       1  2019-09-26 00:00:00    1   
35719       0     0     58  ...         0       0  2021-10-25 00:00:00    1   
35720       1     0     29  ...         0       0  2020-06-29 00:00:00    1   

                         주요사업내용 국가명    직원수  폐업여부   산업코드 대분류  회사설립일  
0               LP Gas 충전 및 판매업   0   43.0     0   도매 및 소매업  20650  
1               가죽 및 대용가죽제품 제조업   0   35.0     0        제조업  11410  
2                         시내버스업   0  149.0     0   운수 및 창고업   7672  
3                     자동차 부품 제조   0   75.0     0        제조업   8694  
4             골프용품 전반의 제조 및 수출업   0    3.0     0   도매 및 소매업   8189  
...                         ...  ..    ...   ...        ...    ...  
35716                  간장게장(장류)   0    0.0     1        제조업   1740  
35717            돈가스, 탕수육, 꿔바로우   0   22.0     1        제조업    827  
35718                    한식, 중식   0    0.0     1  숙박 및 음식점업   1132  
35719  1.인공지능(AI) 솔루션 구축 및 관련사업   0    0.0     1      정보통신업    372  
35720                       NaN   0    0.0     1        제조업    855  

[35721 rows x 21 columns]

In [39]:
num_attribss = df[['직원수','회사설립일']]
cat_1hot_attribs = df[['산업코드 대분류']]
cat_ord_attribs = df[['상장코드','벤처기업여부','공공기관유형', '중견기업보호여부','국가명','국외투자법인여부','개인법인구분','본점지점구분','본점기업코드','설립구분']]
y = company_info[['폐업여부']]

cat_all = df[['산업코드 대분류','상장코드','벤처기업여부','공공기관유형', '중견기업보호여부','국가명','국외투자법인여부','본점지점구분','본점기업코드','설립구분']]
# 변수별 타입 나누기

In [33]:
cat_all.dtypes

산업코드 대분류    object
상장코드         int64
벤처기업여부       int64
공공기관유형       int64
중견기업보호여부     int64
국가명          int64
국외투자법인여부     int64
개인법인구분       int64
본점지점구분       int64
본점기업코드       int64
설립구분         int64
dtype: object

## 스케일링

### StandardScaler

In [13]:
# 수치형 변수 스케일링
sta_scaler = StandardScaler()
sta_X_scale = sta_scaler.fit_transform(num_attribss)
sta_X_scale = pd.DataFrame(sta_X_scale, columns=num_attribss.columns)
sta_X_scale  # 스케일링 데이터 프레임화

직원수     회사설립일
0     -0.071824  3.515949
1     -0.123865  1.242839
2      0.617721  0.323263
3      0.136341  0.574683
4     -0.332029  0.450449
...         ...       ...
35716 -0.351545 -1.136054
35717 -0.208432 -1.360659
35718 -0.351545 -1.285626
35719 -0.351545 -1.472592
35720 -0.351545 -1.353770

[35721 rows x 2 columns]

# MinMaxScaler

In [14]:
MM_scaler = MinMaxScaler()
MM_X_scale = MM_scaler.fit_transform(num_attribss)
MM_X_scale = pd.DataFrame(MM_X_scale, columns=num_attribss.columns)
MM_X_scale  # 스케일링 데이터 프레임화

직원수     회사설립일
0      0.002636  0.414897
1      0.002146  0.228227
2      0.009135  0.152710
3      0.004598  0.173357
4      0.000184  0.163155
...         ...       ...
35716  0.000000  0.032869
35717  0.001349  0.014425
35718  0.000000  0.020586
35719  0.000000  0.005232
35720  0.000000  0.014990

[35721 rows x 2 columns]

## 원핫인코딩

In [15]:
# 원핫인코딩 함수 적용
hot1_encoder = OneHotEncoder(sparse=False,drop='if_binary')
X_1hot = hot1_encoder.fit_transform(cat_1hot_attribs)
X_1hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [16]:
X_1hot = pd.DataFrame(X_1hot, columns=hot1_encoder.get_feature_names()) #순서가 없는 카테고리형
# 데이터 프레임화

C:\Users\yoon9\anaconda3\envs\numble_repo\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [17]:
X_1hot

x0_건설업  x0_공공 행정, 국방 및 사회보장 행정  x0_광업  x0_교육 서비스업  x0_금융 및 보험업  \
0         0.0                     0.0    0.0         0.0          0.0   
1         0.0                     0.0    0.0         0.0          0.0   
2         0.0                     0.0    0.0         0.0          0.0   
3         0.0                     0.0    0.0         0.0          0.0   
4         0.0                     0.0    0.0         0.0          0.0   
...       ...                     ...    ...         ...          ...   
35716     0.0                     0.0    0.0         0.0          0.0   
35717     0.0                     0.0    0.0         0.0          0.0   
35718     0.0                     0.0    0.0         0.0          0.0   
35719     0.0                     0.0    0.0         0.0          0.0   
35720     0.0                     0.0    0.0         0.0          0.0   

       x0_농업,임업 및 어업  x0_도매 및 소매업  x0_보건업 및 사회복지 서비스업  x0_부동산업  \
0                0.0          1.0                 0.0      0.0   
1                0.0          0.0                 0.0      0.0   
2                0.0          0.0                 0.0      0.0   
3                0.0          0.0                 0.0      0.0   
4                0.0          1.0                 0.0      0.0   
...              ...          ...                 ...      ...   
35716            0.0          0.0                 0.0      0.0   
35717            0.0          0.0                 0.0      0.0   
35718            0.0          0.0                 0.0      0.0   
35719            0.0          0.0                 0.0      0.0   
35720            0.0          0.0                 0.0      0.0   

       x0_사업시설 관리, 사업 지원 및 임대 서비스업  x0_수도, 하수 및 폐기물 처리, 원료 재생업  x0_숙박 및 음식점업  \
0                              0.0                         0.0           0.0   
1                              0.0                         0.0           0.0   
2                              0.0                         0.0           0.0   
3                              0.0                         0.0           0.0   
4                              0.0                         0.0           0.0   
...                            ...                         ...           ...   
35716                          0.0                         0.0           0.0   
35717                          0.0                         0.0           0.0   
35718                          0.0                         0.0           1.0   
35719                          0.0                         0.0           0.0   
35720                          0.0                         0.0           0.0   

       x0_예술, 스포츠 및 여가관련 서비스업  x0_운수 및 창고업  x0_전기,가스,증기 및 공기 조절 공급업  \
0                         0.0          0.0                      0.0   
1                         0.0          0.0                      0.0   
2                         0.0          1.0                      0.0   
3                         0.0          0.0                      0.0   
4                         0.0          0.0                      0.0   
...                       ...          ...                      ...   
35716                     0.0          0.0                      0.0   
35717                     0.0          0.0                      0.0   
35718                     0.0          0.0                      0.0   
35719                     0.0          0.0                      0.0   
35720                     0.0          0.0                      0.0   

       x0_전문, 과학 및 기술 서비스업  x0_정보통신업  x0_제조업  x0_협회 및 단체  
0                      0.0       0.0     0.0         0.0  
1                      0.0       0.0     1.0         0.0  
2                      0.0       0.0     0.0         0.0  
3                      0.0       0.0     1.0         0.0  
4                      0.0       0.0     0.0         0.0  
...                    ...       ...     ...         ...  
35716                  0.0       0.0     1.0         0.0  
35717                  0.0       0.0     1.0       

## Oridinal Encoding

In [27]:
ord_encoder = OrdinalEncoder() #순서가 있는 카테고리형
X_ord = ord_encoder.fit_transform(cat_ord_attribs['벤처기업여부'].values.reshape(-1,1))
X_ord = pd.DataFrame(X_ord, columns= ['벤처기업여부'])
X_ord

벤처기업여부
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
...       ...
35716     0.0
35717     0.0
35718     0.0
35719     0.0
35720     1.0

[35721 rows x 1 columns]

## Label Encoding

In [40]:
cat_all['산업코드 대분류']

산업코드 대분류  상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명  국외투자법인여부  본점지점구분  \
0       도매 및 소매업     0       0       0         0    0         0       1   
1            제조업     0       0       0         0    0         0       1   
2       운수 및 창고업     0       0       0         0    0         0       1   
3            제조업     0       0       0         0    0         0       1   
4       도매 및 소매업     0       0       0         0    0         0       1   
...          ...   ...     ...     ...       ...  ...       ...     ...   
35716        제조업     0       0       0         0    0         0       2   
35717        제조업     0       0       0         0    0         0       2   
35718  숙박 및 음식점업     0       0       0         0    0         0       2   
35719      정보통신업     0       0       0         0    0         0       1   
35720        제조업     0       1       0         0    0         0       1   

       본점기업코드  설립구분  
0           0     1  
1           0     1  
2           0     1  
3           0     1  
4           0     1  
...       ...   ...  
35716       1     1  
35717       1     1  
35718       1     1  
35719       0     1  
35720       0     1  

[35721 rows x 10 columns]

In [42]:
lab_encoder = LabelEncoder()  #순서가 있는 카테고리형
cat_all['산업코드 대분류'] = lab_encoder.fit_transform(cat_all['산업코드 대분류'])

C:\Users\yoon9\AppData\Local\Temp\ipykernel_17544\3556145079.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_all['산업코드 대분류'] = lab_encoder.fit_transform(cat_all['산업코드 대분류'])


In [45]:
cat_all['설립구분'] = lab_encoder.fit_transform(cat_all['설립구분'])


C:\Users\yoon9\AppData\Local\Temp\ipykernel_17544\2116850998.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_all['설립구분'] = lab_encoder.fit_transform(cat_all['설립구분'])


In [47]:
cat_all

산업코드 대분류  상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명  국외투자법인여부  본점지점구분  \
0             6     0       0       0         0    0         0       1   
1            17     0       0       0         0    0         0       1   
2            13     0       0       0         0    0         0       1   
3            17     0       0       0         0    0         0       1   
4             6     0       0       0         0    0         0       1   
...         ...   ...     ...     ...       ...  ...       ...     ...   
35716        17     0       0       0         0    0         0       2   
35717        17     0       0       0         0    0         0       2   
35718        11     0       0       0         0    0         0       2   
35719        16     0       0       0         0    0         0       1   
35720        17     0       1       0         0    0         0       1   

       본점기업코드  설립구분  
0           0     0  
1           0     0  
2           0     0  
3           0     0  
4           0     0  
...       ...   ...  
35716       1     0  
35717       1     0  
35718       1     0  
35719       0     0  
35720       0     0  

[35721 rows x 10 columns]

In [48]:
df_preprdcessed_sta = pd.concat([sta_X_scale, X_1hot, X_ord], axis = 1)
df_preprdcessed_sta
# Standard Scaler + One Hot + Ordinal

직원수     회사설립일  x0_건설업  x0_공공 행정, 국방 및 사회보장 행정  x0_광업  x0_교육 서비스업  \
0     -0.071824  3.515949     0.0                     0.0    0.0         0.0   
1     -0.123865  1.242839     0.0                     0.0    0.0         0.0   
2      0.617721  0.323263     0.0                     0.0    0.0         0.0   
3      0.136341  0.574683     0.0                     0.0    0.0         0.0   
4     -0.332029  0.450449     0.0                     0.0    0.0         0.0   
...         ...       ...     ...                     ...    ...         ...   
35716 -0.351545 -1.136054     0.0                     0.0    0.0         0.0   
35717 -0.208432 -1.360659     0.0                     0.0    0.0         0.0   
35718 -0.351545 -1.285626     0.0                     0.0    0.0         0.0   
35719 -0.351545 -1.472592     0.0                     0.0    0.0         0.0   
35720 -0.351545 -1.353770     0.0                     0.0    0.0         0.0   

       x0_금융 및 보험업  x0_농업,임업 및 어업  x0_도매 및 소매업  x0_보건업 및 사회복지 서비스업  ...  \
0              0.0            0.0          1.0                 0.0  ...   
1              0.0            0.0          0.0                 0.0  ...   
2              0.0            0.0          0.0                 0.0  ...   
3              0.0            0.0          0.0                 0.0  ...   
4              0.0            0.0          1.0                 0.0  ...   
...            ...            ...          ...                 ...  ...   
35716          0.0            0.0          0.0                 0.0  ...   
35717          0.0            0.0          0.0                 0.0  ...   
35718          0.0            0.0          0.0                 0.0  ...   
35719          0.0            0.0          0.0                 0.0  ...   
35720          0.0            0.0          0.0                 0.0  ...   

       x0_수도, 하수 및 폐기물 처리, 원료 재생업  x0_숙박 및 음식점업  x0_예술, 스포츠 및 여가관련 서비스업  \
0                             0.0           0.0                     0.0   
1                             0.0           0.0                     0.0   
2                             0.0           0.0                     0.0   
3                             0.0           0.0                     0.0   
4                             0.0           0.0                     0.0   
...                           ...           ...                     ...   
35716                         0.0           0.0                     0.0   
35717                         0.0           0.0                     0.0   
35718                         0.0           1.0                     0.0   
35719                         0.0           0.0                     0.0   
35720                         0.0           0.0                     0.0   

       x0_운수 및 창고업  x0_전기,가스,증기 및 공기 조절 공급업  x0_전문, 과학 및 기술 서비스업  x0_정보통신업  \
0              0.0                      0.0                  0.0       0.0   
1              0.0                      0.0                  0.0       0.0   
2              1.0                      0.0                  0.0       0.0   
3              0.0                      0.0                  0.0       0.0   
4              0.0                      0.0                  0.0       0.0   
...            ...                      ...                  ...       ...   
35716          0.0                      0.0                  0.0       0.0   
35717          0.0                      0.0                  0.0       0.0   
35718          0.0                      0.0                  0.0       0.0   
35719          0.0                      0.0                  0.0       1.0   
35720          0.0                      0.0                  0.0       0.0   

       x0_제조업  x0_협회 및 단체  벤처기업여부  
0         0.0         0.0     0.0  
1         1.0         0.0     0.0  
2         0.0         0.0     0.0  
3         1.0         0.0     0.0  
4         0.0         0.0     0.0  
...       ...         ...     ...  
35716     1.0         0.0     0.0  
35717     1.0         0.

In [24]:
df_preprdcessed_MM = pd.concat([MM_X_scale, X_1hot, X_ord], axis = 1)
df_preprdcessed_MM
#Min Max Scaler + One Hot + Ordinal

직원수     회사설립일  x0_건설업  x0_공공 행정, 국방 및 사회보장 행정  x0_광업  x0_교육 서비스업  \
0      0.002636  0.414897     0.0                     0.0    0.0         0.0   
1      0.002146  0.228227     0.0                     0.0    0.0         0.0   
2      0.009135  0.152710     0.0                     0.0    0.0         0.0   
3      0.004598  0.173357     0.0                     0.0    0.0         0.0   
4      0.000184  0.163155     0.0                     0.0    0.0         0.0   
...         ...       ...     ...                     ...    ...         ...   
35716  0.000000  0.032869     0.0                     0.0    0.0         0.0   
35717  0.001349  0.014425     0.0                     0.0    0.0         0.0   
35718  0.000000  0.020586     0.0                     0.0    0.0         0.0   
35719  0.000000  0.005232     0.0                     0.0    0.0         0.0   
35720  0.000000  0.014990     0.0                     0.0    0.0         0.0   

       x0_금융 및 보험업  x0_농업,임업 및 어업  x0_도매 및 소매업  x0_보건업 및 사회복지 서비스업  ...  x5_5  \
0              0.0            0.0          1.0                 0.0  ...   0.0   
1              0.0            0.0          0.0                 0.0  ...   0.0   
2              0.0            0.0          0.0                 0.0  ...   0.0   
3              0.0            0.0          0.0                 0.0  ...   0.0   
4              0.0            0.0          1.0                 0.0  ...   0.0   
...            ...            ...          ...                 ...  ...   ...   
35716          0.0            0.0          0.0                 0.0  ...   0.0   
35717          0.0            0.0          0.0                 0.0  ...   0.0   
35718          0.0            0.0          0.0                 0.0  ...   0.0   
35719          0.0            0.0          0.0                 0.0  ...   0.0   
35720          0.0            0.0          0.0                 0.0  ...   0.0   

       x5_6  x5_7  x5_10  x5_99  상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명  
0       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
1       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
2       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
3       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
4       0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
...     ...   ...    ...    ...   ...     ...     ...       ...  ...  
35716   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35717   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35718   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35719   0.0   0.0    0.0    0.0   0.0     0.0     0.0       0.0  0.0  
35720   0.0   0.0    0.0    0.0   0.0     1.0     0.0       0.0  0.0  

[35721 rows x 38 columns]

In [49]:
df_preprdcessed_sta_label = pd.concat([sta_X_scale, cat_all], axis = 1)
df_preprdcessed_sta_label

# Standard scaler + Label encoding

직원수     회사설립일  산업코드 대분류  상장코드  벤처기업여부  공공기관유형  중견기업보호여부  국가명  \
0     -0.071824  3.515949         6     0       0       0         0    0   
1     -0.123865  1.242839        17     0       0       0         0    0   
2      0.617721  0.323263        13     0       0       0         0    0   
3      0.136341  0.574683        17     0       0       0         0    0   
4     -0.332029  0.450449         6     0       0       0         0    0   
...         ...       ...       ...   ...     ...     ...       ...  ...   
35716 -0.351545 -1.136054        17     0       0       0         0    0   
35717 -0.208432 -1.360659        17     0       0       0         0    0   
35718 -0.351545 -1.285626        11     0       0       0         0    0   
35719 -0.351545 -1.472592        16     0       0       0         0    0   
35720 -0.351545 -1.353770        17     0       1       0         0    0   

       국외투자법인여부  본점지점구분  본점기업코드  설립구분  
0             0       1       0     0  
1             0       1       0     0  
2             0       1       0     0  
3             0       1       0     0  
4             0       1       0     0  
...         ...     ...     ...   ...  
35716         0       2       1     0  
35717         0       2       1     0  
35718         0       2       1     0  
35719         0       1       0     0  
35720         0       1       0     0  

[35721 rows x 12 columns]

In [28]:
X = df_preprdcessed_sta

In [30]:
X.shape, y.shape

((35721, 38), (35721, 1))

# Standard Scaler + One Hot + Ordinal Random Forest

In [57]:
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, shuffle=True, stratify=y, random_state=42)
X_train.shape, X_val.shape, y_train.shape, y_val.shape

NameError: name 'X' is not defined

In [34]:
y.value_counts()

폐업여부
0       28982
1        6739
dtype: int64

## 모델 평가 함수

In [68]:
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [69]:
def model_eval(pred, answer):
    print(f'accuracy_score : {accuracy_score(pred,answer)}')
    print(f'recall_score : {recall_score(pred,answer)}')
    print(f'precision_score : {precision_score(pred,answer)}')
    print(f'f1_score : {f1_score(pred,answer)}')
    print(f'coufusion_matrix : ')
    print(confusion_matrix(pred,answer))

## 랜덤포레스트 모델 학습

In [61]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
RFC_sta = RandomForestClassifier(max_depth=10,n_estimators=100)

In [57]:
RFC_sta.fit(X_train,y_train)

C:\Users\yoon9\AppData\Local\Temp\ipykernel_13960\1307098183.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFC_sta.fit(X_train,y_train)


RandomForestClassifier(max_depth=10)

In [58]:
X_train_predicted = RFC_sta.predict(X_train)

In [59]:
X_val_predicted = RFC_sta.predict(X_val)

In [60]:
model_eval(X_train_predicted,y_train)

accuracy_score : 0.8606872900335947
recall_score : 0.8344402277039848
precision_score : 0.3262845483212762
f1_score : 0.4691292172289638
coufusion_matrix : 
[[22836  3632]
 [  349  1759]]


In [61]:
model_eval(X_val_predicted,y_val)

accuracy_score : 0.8531840447865641
recall_score : 0.793713163064833
precision_score : 0.2997032640949555
f1_score : 0.43511039310716215
coufusion_matrix : 
[[5692  944]
 [ 105  404]]


# Minmax Scaler + One Hot + Ordinal Random Forest

In [50]:
X_MM = df_preprdcessed_sta_label

In [51]:
y

폐업여부
0         0
1         0
2         0
3         0
4         0
...     ...
35716     1
35717     1
35718     1
35719     1
35720     1

[35721 rows x 1 columns]

In [68]:
X_train_MM, X_val_MM, y_train_MM, y_val_MM = train_test_split(X_MM, y, test_size=0.2, shuffle=True, stratify=y, random_state=42)
X_train_MM.shape, X_val_MM.shape, y_train_MM.shape, y_val_MM.shape

((28576, 38), (7145, 38), (28576, 1), (7145, 1))

In [75]:
RFC_MM = RandomForestClassifier()

In [76]:
RFC_MM.fit(X_train_MM,y_train_MM)

C:\Users\yoon9\AppData\Local\Temp\ipykernel_13960\3340015268.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFC_MM.fit(X_train_MM,y_train_MM)


RandomForestClassifier()

In [77]:
X_train_predicted_MM = RFC_MM.predict(X_train_MM)

In [78]:
X_val_predicted_MM = RFC_MM.predict(X_val_MM)

In [79]:
model_eval(X_train_predicted_MM,y_train_MM)

accuracy_score : 0.9896416573348265
recall_score : 0.9875598086124402
precision_score : 0.9571508069003896
f1_score : 0.9721175584024114
coufusion_matrix : 
[[23120   231]
 [   65  5160]]


In [80]:
model_eval(X_val_predicted_MM,y_val_MM)

accuracy_score : 0.8219734079776068
recall_score : 0.5355140186915888
precision_score : 0.4250741839762611
f1_score : 0.47394540942928043
coufusion_matrix : 
[[5300  775]
 [ 497  573]]


MinMax 를 사용하자 오버피팅 현상이 발생하였다.

## Standard Scaler + Label encoding Random Forest

In [52]:
X_sl = df_preprdcessed_sta_label

In [53]:
y

폐업여부
0         0
1         0
2         0
3         0
4         0
...     ...
35716     1
35717     1
35718     1
35719     1
35720     1

[35721 rows x 1 columns]

In [58]:
X_train_sl, X_val_sl, y_train_sl, y_val_sl = train_test_split(X_sl, y, test_size=0.2, shuffle=True, stratify=y, random_state=42)
X_train_sl.shape, X_val_sl.shape, y_train_sl.shape, y_val_sl.shape

((28576, 12), (7145, 12), (28576, 1), (7145, 1))

In [62]:
RFC_sl = RandomForestClassifier()

In [63]:
RFC_sl.fit(X_train_sl,y_train_sl)

C:\Users\yoon9\AppData\Local\Temp\ipykernel_17544\1300462302.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFC_sl.fit(X_train_sl,y_train_sl)


RandomForestClassifier()

In [64]:
X_train_predicted_sl = RFC_sl.predict(X_train_sl)

In [65]:
X_val_predicted_sl = RFC_sl.predict(X_val_sl)

In [70]:
model_eval(X_train_predicted_sl,y_train_sl)

accuracy_score : 0.9895716685330347
recall_score : 0.9873684210526316
precision_score : 0.956965312557967
f1_score : 0.9719291635267521
coufusion_matrix : 
[[23119   232]
 [   66  5159]]


In [71]:
model_eval(X_val_predicted_sl,y_val_sl)

accuracy_score : 0.8229531140657803
recall_score : 0.5405669599217986
precision_score : 0.4102373887240356
f1_score : 0.46646984394770136
coufusion_matrix : 
[[5327  795]
 [ 470  553]]


# LightGBM

In [1]:
import lightgbm as lgby

ModuleNotFoundError: No module named 'lightgbm'

In [100]:
# LightGBM 전용 데이터셋 생성
dtrain = lgb.Dataset(X_train, y_train) # LightGBM 전용 훈련 데이터셋
dvalid = lgb.Dataset(X_valid, y_valid) # LightGBM 전용 검증 데이터셋
# LightGBM 모델 훈련
lgb_model = lgb.train(params=max_params, # 최적 하이퍼파라미터 1
                        train_set=dtrain, # 훈련 데이터셋
                        num_boost_round=2500, # 부스팅 반복 횟수
                        valid_sets=dvalid, # 성능 평가용 검증 데이터셋
                        feval=gini, # 검증용 평가지표
                        early_stopping_rounds=300, # 조기종료 조건
                        verbose_eval=100) # 100번째마다 점수 출력

# 테스트 데이터를 활용해 OOF 예측
oof_test_preds += lgb_model.predict(X_test)/folds.n_splits
# 모델 성능 평가를 위한 검증 데이터 타깃값 예측
oof_val_preds[valid_idx] += lgb_model.predict(X_valid)
# 검증 데이터 예측 확률에 대한 정규화 지니계수
gini_score = eval_gini(y_valid, oof_val_preds[valid_idx])
print(f'폴드 {idx+1} 지니계수 : {gini_score}\n')

NameError: name 'lgb' is not defined